#ifndef ENGINE_MAJOR_VERSION
#define ENGINE_MAJOR_VERSION 1
#endif // !ENGINE_MAJOR_VERSION

#ifndef ENGINE_MINOR_VERSION
#define ENGINE_MINOR_VERSION 1
#endif // !ENGINE_MONOR_VERSION

#ifndef ENGINE_NAME
#define ENGINE_NAME "POLYP"
#endif // !ENGINE_MONOR_VERSION

#ifndef ENGINE_VK_VERSION
#define ENGINE_VK_VERSION VK_API_VERSION_1_2
#endif // !ENGINE_VK_VERSION
